service: mox-galleria

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  stage: prod
  region: us-west-2
  runtime: nodejs18.x
  profile: mox-galleria-deploy
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - arn:aws:dynamodb:*:*:table/mox_galleria*
            - arn:aws:dynamodb:*:*:global-table/mox_galleria*

functions:
  addMtgCard:
    handler: backend/src/handler/addMtgCard.addMtgCard
    events:
      - http:
          method: POST
          path: cards/mtg
  getMtgCard:
    handler: backend/src/handler/getMtgCard.getMtgCard
    events:
      - http:
          method: GET
          path: v1/cards/mtg/{id}
  addMtgAlter:
    handler: backend/src/handler/addMtgAlter.addMtgAlter
    events:
      - http:
          method: POST
          path: v1/alters/mtg